image: mapret/cppimage:v1

stages:
  - build
  - test

build:
  stage: build
  script:
   - apk add flex bison
   - mkdir build && cd build
   - cmake -DCMAKE_BUILD_TYPE=Release ..
   - cmake --build .
  artifacts:
    paths:
     - build/test/Calculator-test

test:
  stage: test
  script:
   - build/test/Calculator-test
