image: conanio/gcc8

stages:
  - build
  - test

build:
  stage: build
  script:
   - sudo apt update
   - sudo apt install flex bison --yes
   - mkdir build && cd build
   - cmake -DCMAKE_BUILD_TYPE=Release ..
   - cmake --build .
  artifacts:
    paths:
     - build/test/Calculator-test

test:
  stage: test
  script:
   - build/test/Calculator-test
